### ISSUE TITLE
Improve Initialization of Validators with a Single ED25519 Reward Address and Enhanced GUI Features

### ISSUE THREAD

**Issue by Ja7ad** [pactus-project/pactus#1555]
## Description

The current implementation generates validators with individual reward addresses during the initial setup of a blockchain node. To optimize this process, we propose an improvement where a single ED25519 reward address is used for all validators during initialization, while maintaining flexibility for the number of validators. This update will include modifications to the node setup process, improvements to the reward address handling, and changes to the GUI for better clarity and control over validator visibility.

## Subtasks

- [ ] Generate 7 to 32 Validators with a Single Reward Account Address During Initial Node Setup
- [ ] Change slice of `reward_addresses` to key/value map
- [ ] Hide/Unhide unbonded validators in GUI
- [ ] Separating validators List and accounts in tabbed GUI

**Comment by aboka2k** [comment]
Looking forward to the updates. Thanks for your hard work!
